name: Build (Generated)
on:
  push:
    branches:
      - main
  pull_request:
env:
  LANG: en_US.UTF-8
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Artifact Cache Repository
        id: artifact-cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Build
        run: |
          ./mvnw clean package -DskipTests=true
      - name: Test
        run: |
          ./mvnw verify
